// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQEgj8BfNz9QJ8sZOmXkPBZW1d-3-_HjI',
    appId: '1:703620350242:web:11ff89168340520534257b',
    messagingSenderId: '703620350242',
    projectId: 'my-talk-app-flutter-project',
    authDomain: 'my-talk-app-flutter-project.firebaseapp.com',
    storageBucket: 'my-talk-app-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUsOJ0pBET0DY3YXCp-svmd_RSQ3J1_lY',
    appId: '1:703620350242:android:671c38588fff6ca834257b',
    messagingSenderId: '703620350242',
    projectId: 'my-talk-app-flutter-project',
    storageBucket: 'my-talk-app-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmwL12FIZiQCorIT6mNNA-O73OSX7ohN4',
    appId: '1:703620350242:ios:cb6e2e09b9aa08c134257b',
    messagingSenderId: '703620350242',
    projectId: 'my-talk-app-flutter-project',
    storageBucket: 'my-talk-app-flutter-project.appspot.com',
    iosClientId: '703620350242-oh6dt24el8eq72nt4ddig5ke7tcp8shr.apps.googleusercontent.com',
    iosBundleId: 'com.darlhp.talkapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmwL12FIZiQCorIT6mNNA-O73OSX7ohN4',
    appId: '1:703620350242:ios:cb6e2e09b9aa08c134257b',
    messagingSenderId: '703620350242',
    projectId: 'my-talk-app-flutter-project',
    storageBucket: 'my-talk-app-flutter-project.appspot.com',
    iosClientId: '703620350242-oh6dt24el8eq72nt4ddig5ke7tcp8shr.apps.googleusercontent.com',
    iosBundleId: 'com.darlhp.talkapp',
  );
}
